apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: worker
  namespace: user-hao-li
spec:
  components:
    - name: worker
      type: webservice
      properties:
        image: "lihao2000b/xcal:1.0"
        clusters: ["local"]
        namespace: user-hao-li
        cmd: ["bash", "/config/runner.sh"]
        env:
          - name: QUEUE_BASE_URL
            value: "http://work-queue.user-hao-li:8009"
      traits:
        - type: scaler
          properties:
            replicas: 5
        - type: storage
          properties:
            configMap:
              - name: config-worker
                mountPath: /config
                data:
                  runner.sh: |
                    git clone --branch main https://oauth2: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@github.com/lihao2000B/Xcal.git ~/Xcal
                    cd ~/Xcal/worker
                    pip install msoffcrypto-tool
                    python worker.py
